2025-10-14 21:58:12.432 INFO {MainThread} [main] (<module>) {D:\Project\V1\FlowKit\src\FlowKitControlUint\main.py:105} Starting FastAPI app at 0.0.0.0:9500
2025-10-14 21:58:12.492 INFO {MainThread} [main] (lifespan) {D:\Project\V1\FlowKit\src\FlowKitControlUint\main.py:35} Starting FlowKit Control Unit lifespan
2025-10-14 21:58:12.527 INFO {MainThread} [fcb_queue] (__init__) {D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb_queue.py:23} Initialized FlowControlBlockQueue with MongoDB connection
2025-10-14 21:58:12.527 INFO {MainThread} [fcb_queue] (recover_from_storage) {D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb_queue.py:27} Starting recovery of FlowControlBlocks from MongoDB
2025-10-14 21:58:12.578 INFO {MainThread} [main] (lifespan) {D:\Project\V1\FlowKit\src\FlowKitControlUint\main.py:39} Recovered FCB_QUEUE from storage
2025-10-14 21:58:18.041 INFO {MainThread} [main] (log_requests) {D:\Project\V1\FlowKit\src\FlowKitControlUint\main.py:48} Incoming request: POST http://127.0.0.1:9500/fcb/add
2025-10-14 21:58:18.042 INFO {MainThread} [main] (add_fcb) {D:\Project\V1\FlowKit\src\FlowKitControlUint\main.py:60} Add FCB request received with nodes: ['start', 'node1']
2025-10-14 21:58:18.042 INFO {MainThread} [flow] (__init__) {D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb\flow.py:12} Flow initialized with 2 nodes
2025-10-14 21:58:18.043 INFO {MainThread} [flow_control_block] (__init__) {D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb\flow_control_block.py:26} FlowControlBlock c7d42e36-faa9-477c-b22c-fd3be8867174 initialized in QUEUED state
2025-10-14 21:58:18.043 INFO {MainThread} [fcb_queue] (add_fcb) {D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb_queue.py:107} \u2795 Added new FlowControlBlock with id c7d42e36-faa9-477c-b22c-fd3be8867174
2025-10-14 21:58:18.043 INFO {MainThread} [flow_control_block] (start) {D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb\flow_control_block.py:29} FlowControlBlock c7d42e36-faa9-477c-b22c-fd3be8867174 starting
2025-10-14 21:58:18.043 INFO {MainThread} [flow_control_block] (exec) {D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb\flow_control_block.py:71} Submitting next node execution for flow c7d42e36-faa9-477c-b22c-fd3be8867174
2025-10-14 21:58:18.043 INFO {ThreadPoolExecutor-1_0} [flow] (get_curr_node) {D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb\flow.py:24} Getting current node: start
2025-10-14 21:58:18.044 INFO {ThreadPoolExecutor-1_0} [flow] (get_curr_inp) {D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb\flow.py:28} Getting current input data: {}
2025-10-14 21:58:18.044 INFO {ThreadPoolExecutor-1_0} [flow_control_block] (_run_node) {D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb\flow_control_block.py:56} Executing node 'start' in flow c7d42e36-faa9-477c-b22c-fd3be8867174
2025-10-14 21:58:18.044 INFO {ThreadPoolExecutor-1_0} [node] (run) {D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb\node.py:55} Executing node 'start' [runner_id=1b77a90f-111f-4abc-bdb5-809a8b57dddc] with inputs: {}
2025-10-14 21:58:18.044 INFO {ThreadPoolExecutor-1_0} [node] (run) {D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb\node.py:58} Sending POST to http://127.0.0.1:8500/nodes/add-node with payload keys: ['node_name', 'code', 'inputs', 'runner_id']
2025-10-14 21:58:18.043 INFO {MainThread} [fcb_queue] (start_fcb) {D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb_queue.py:115} \u25b6\ufe0f Started FlowControlBlock c7d42e36-faa9-477c-b22c-fd3be8867174
2025-10-14 21:58:18.045 INFO {MainThread} [main] (add_fcb) {D:\Project\V1\FlowKit\src\FlowKitControlUint\main.py:70} Flow Control Block added successfully with ID: c7d42e36-faa9-477c-b22c-fd3be8867174
2025-10-14 21:58:18.045 INFO {MainThread} [main] (log_requests) {D:\Project\V1\FlowKit\src\FlowKitControlUint\main.py:50} Response status: 200 for POST http://127.0.0.1:9500/fcb/add
2025-10-14 21:58:20.958 INFO {ThreadPoolExecutor-1_0} [_client] (_send_single_request) {D:\Project\V1\FlowKit\.conda\Lib\site-packages\httpx\_client.py:1025} HTTP Request: POST http://127.0.0.1:8500/nodes/add-node "HTTP/1.1 200 OK"
2025-10-14 21:58:20.959 INFO {ThreadPoolExecutor-1_0} [node] (run) {D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb\node.py:63} Response from runner received for node 'start': {'node_name': 'start', 'runner_id': '1b77a90f-111f-4abc-bdb5-809a8b57dddc', 'code_base64': 'ZnJvbSBmbG93a2l0Lm5vZGUgaW1wb3J0IE5vZGUKZnJvbSBmbG93a2l0LmxvZyBpbXBvcnQgTG9nZ2VyCgpub2RlID0gTm9kZSgpCmxvZ2dlciA9IExvZ2dlcihub2RlKQoKYXN5bmMgZGVmIG1haW4oKToKICAgICMgbm9kZXMsIG91dHB1dCwgbWVzc2FnZQogICAgaW5wdXRzID0gbm9kZS5nZXRfaW5wdXRzKCkKICAgIHJldHVybiBbIm5vZGUxIl0sIHsiYSI6MSwgImIiOjJ9LCAicnVuIHN1Y2Nlc3NmdWxseSIKCm5vZGUucmVnaXN0ZXJfbWFpbihtYWluKQpub2RlLnJ1bigpCg==', 'status': 'DONE', 'inputs': {}, 'logs': [], 'outputs': {'nodes': ['node1'], 'outputs': {'a': 1, 'b': 2}, 'status': 'DONE', 'message': 'run successfully'}}
2025-10-14 21:58:20.959 INFO {ThreadPoolExecutor-1_0} [node] (run) {D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb\node.py:67} Node 'start' execution completed successfully [runner_id=1b77a90f-111f-4abc-bdb5-809a8b57dddc]
2025-10-14 21:58:20.960 ERROR {ThreadPoolExecutor-1_0} [node] (run) {D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb\node.py:115} \u274c Unexpected error in node 'start': 1 validation error for NodeExecutionData
code
  Field required [type=missing, input_value={'node_name': 'start', 'r...age='run successfully')}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/missing
Traceback (most recent call last):
  File "D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb\node.py", line 74, in run
    return NodeExecutionData(
        node_name=self.name,
    ...<5 lines>...
        outputs=_output,
    )
  File "D:\Project\V1\FlowKit\.conda\Lib\site-packages\pydantic\main.py", line 250, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for NodeExecutionData
code
  Field required [type=missing, input_value={'node_name': 'start', 'r...age='run successfully')}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/missing
2025-10-14 21:58:20.963 ERROR {ThreadPoolExecutor-1_0} [flow_control_block] (_run_node) {D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb\flow_control_block.py:63} Exception while executing node 'start' in flow c7d42e36-faa9-477c-b22c-fd3be8867174: 1 validation error for NodeExecutionData
code
  Field required [type=missing, input_value={'node_name': 'start', 'r...ic.dev/2.12/v/missing")}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/missing
Traceback (most recent call last):
  File "D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb\flow_control_block.py", line 58, in _run_node
    result = curr_node.run(curr_inp)
  File "D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb\node.py", line 116, in run
    return NodeExecutionData(
        node_name=self.name,
    ...<5 lines>...
        outputs=NodeOutputs(nodes=[], outputs={}, status="error", message=str(e)),
    )
  File "D:\Project\V1\FlowKit\.conda\Lib\site-packages\pydantic\main.py", line 250, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for NodeExecutionData
code
  Field required [type=missing, input_value={'node_name': 'start', 'r...ic.dev/2.12/v/missing")}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/missing
2025-10-14 21:59:06.699 INFO {MainThread} [fcb_queue] (clean_up) {D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb_queue.py:143} Cleaning up all FlowControlBlocks
2025-10-14 21:59:06.699 INFO {MainThread} [flow_control_block] (stop) {D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb\flow_control_block.py:34} FlowControlBlock c7d42e36-faa9-477c-b22c-fd3be8867174 stopping
2025-10-14 21:59:06.699 INFO {MainThread} [fcb_queue] (clean_up) {D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb_queue.py:147} \U0001f6d1 Stopped FlowControlBlock c7d42e36-faa9-477c-b22c-fd3be8867174 during cleanup
2025-10-14 21:59:06.705 INFO {MainThread} [fcb_queue] (clean_up) {D:\Project\V1\FlowKit\src\FlowKitControlUint\controlunit\fcb_queue.py:154} \U0001f9fd Cleaned up FlowControlBlockQueue resources
2025-10-14 21:59:06.705 INFO {MainThread} [main] (lifespan) {D:\Project\V1\FlowKit\src\FlowKitControlUint\main.py:42} Cleaned up FCB_QUEUE and shutting down
